# codemagic.yaml
# Este arquivo define os workflows de build para o seu projeto Flutter no CodeMagic.

workflows:
  # ===================================================================
  # === WORKFLOW PARA O FLAVOR DE DESENVOLVIMENTO (DEV) =============
  # ===================================================================
  build-dev-flavor:
    name: 'Build DEV Flavor (Android, iOS, Web)'
    instance_type: macos_m2_instance # Constrói na máquina macOS M2, como solicitado.
    max_build_duration: 60 # Duração máxima de 60 minutos para o build.
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main' # Aciona o build em pushes para a branch 'main'.
          include: true
    environment:
      flutter: 3.16.0 # Versão específica do Flutter.
      xcode: 16.4 # Versão específica do Xcode.
      cocoapods: default # Usa a versão padrão do CocoaPods.
      vars:
        # Variáveis usadas para gerar o arquivo dart-define dinamicamente.
        FLAVOR: "DEV"
    scripts:
      - name: 'Gerar arquivo .env/dart-define-dev.json'
        script: |
          # Cria o diretório .env se ele não existir.
          mkdir -p .env

          # Cria o arquivo JSON dinamicamente dentro da pasta .env.
          echo "Gerando .env/dart-define-dev.json..."
          echo "{" > .env/dart-define-dev.json
          echo '  "FLAVOR": "'$FLAVOR'"' >> .env/dart-define-dev.json
          echo "}" >> .env/dart-define-dev.json
          
          echo "Conteúdo do arquivo gerado:"
          cat .env/dart-define-dev.json

      - name: 'Instalar dependências'
        script: |
          flutter packages pub get

      - name: 'Verificar ambiente Flutter'
        script: |
          flutter doctor -v

      - name: 'Build Android (APK) - DEV'
        script: |
          flutter build apk --release \
            --dart-define-from-file=dart-define-dev.json
      
      - name: 'Build iOS - DEV'
        script: |
          flutter build ios --release \
            --dart-define-from-file=dart-define-dev.json

      - name: 'Build Web - DEV'
        script: |
          flutter build web --release \
            --dart-define-from-file=dart-define-dev.json
    artifacts:
      # Coleta os artefatos de build para download.
      - build/app/outputs/apk/release/*.apk
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Release-iphoneos/*.app
      - build/web/**
