# codemagic.yaml
# Versão corrigida com o instance_type correto e caminhos de build ajustados.

workflows:
  # ===================================================================
  # === WORKFLOW PARA O FLAVOR DE DESENVOLVIMENTO (DEV) =============
  # ===================================================================
  build-dev-flavor:
    name: 'Build DEV Flavor (Android, iOS, Web)'
    instance_type: mac_mini_m2 # CORRIGIDO: Este é o nome correto da instância.
    max_build_duration: 60
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
    environment:
      flutter: 3.16.0
      xcode: 16.4
      cocoapods: default
      vars:
        # Renomeado para evitar conflito com a variável de ambiente do CodeMagic
        FLAVOR_VALUE: "DEV" 
    scripts:
      - name: 'Gerar arquivo .env/dart-define-dev.json'
        script: |
          mkdir -p .env
          echo "Gerando .env/dart-define-dev.json..."
          echo "{" > .env/dart-define-dev.json
          echo '  "FLAVOR": "'$FLAVOR_VALUE'"' >> .env/dart-define-dev.json
          echo "}" >> .env/dart-define-dev.json
          echo "Conteúdo do arquivo gerado:"
          cat .env/dart-define-dev.json

      - name: 'Instalar dependências'
        script: |
          flutter packages pub get

      - name: 'Build Android (APK) - DEV'
        script: |
          flutter build apk --release \
            --dart-define-from-file=.env/dart-define-dev.json # CORRIGIDO: Caminho completo para o arquivo.
      
      - name: 'Build iOS - DEV'
        script: |
          flutter build ios --release \
            --dart-define-from-file=.env/dart-define-dev.json # CORRIGIDO: Caminho completo para o arquivo.

      - name: 'Build Web - DEV'
        script: |
          flutter build web --release \
            --dart-define-from-file=.env/dart-define-dev.json # CORRIGIDO: Caminho completo para o arquivo.
    artifacts:
      - build/app/outputs/apk/release/*.apk
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Release-iphoneos/*.app
      - build/web/**
